# Generated by Django 4.2.3 on 2023-12-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
